sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"chenChuy\", \"password\":\"123\"},{\"id\":8, \"username\":\"def\", \"password\":\"456\"},{\"id\":9, \"username\":\"charles\", \"password\":\"789\"},{\"id\":99, \"username\":\"abc\", \"password\":\"123456\"}]"


spring:
  application:
    name: user-service


server:
  port: 8101


eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

      
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        
